export default [
  {
    key: "0",
    title: "balance trainer single leg kneeling good morning",
    reps: 6,
    min: 0,
    sec: 30,
    liked: false,
    mode: 'r1',
  },
  {
    key: "1",
    title: "crunches",
    reps: 8,
    min: 1,
    sec: 0,
    liked: true,
    mode: 't2',
  },
  {
    key: "2",
    title: "deadlift",
    reps: 8,
    min: 0,
    sec: 0,
    liked: true,
    mode: 'r2',
  },
  {
    key: "3",
    title: "flutter kicks",
    reps: 0,
    min: 1,
    sec: 0,
    liked: false,
    mode: 't1',
  },
  {
    key: "4",
    title: "glute ham raise",
    reps: 16,
    min: 0,
    sec: 45,
    liked: false,
    mode: 't2',
  },
  {
    key: "5",
    title: "handstand push up",
    reps: 2,
    min: 0,
    sec: 0,
    liked: true,
    mode: 'r1',
  },
  {
    key: "6",
    title: "inverted row",
    reps: 12,
    min: 0,
    sec: 30,
    liked: false,
    mode: 'r2',
  },{
    key: "7",
    title: "kettlebell front squat",
    reps: 0,
    min: 2,
    sec: 0,
    liked: true,
    mode: 't2',
  },{
    key: "8",
    title: "pike push up",
    reps: 12,
    min: 1,
    sec: 15,
    liked: false,
    mode: 't1',
  },{
    key: "9",
    title: "side bridge",
    reps: 0,
    min: 1,
    sec: 45,
    liked: false,
    mode: 't2',
  },
];